FROM ubuntu:latest

# Atualize os pacotes e instale o ping
RUN apt-get update && \
    apt-get install -y iputils-ping

# Instale o Python e outros pacotes, se necessário
RUN apt-get install -y python3

# Copie seus arquivos fonte para o contêiner
COPY . /app

# Defina um diretório de trabalho no contêiner
WORKDIR /app

# Comando padrão para executar o script de inicialização
CMD ["python3", "main.py"]