FROM node:latest

# Atualize os pacotes e instale o ping
RUN apt-get update && \
    apt-get install -y iputils-ping

# Copie seus arquivos fonte para o contêiner
COPY . /app

# Defina um diretório de trabalho no contêiner
WORKDIR /app

# Comando padrão para executar o script de inicialização
CMD ["node", "./js/test.js"]
